/*
============================================
; Title: not-found.component.ts
; Author: Devan Wong
; Date: 2 April 2021
; Description: not-found component page
;===========================================
*/
// This was autogenerated.
import { Component, OnInit } from '@angular/core';

@Component({
  selector: 'app-not-found',
  templateUrl: './not-found.component.html',
  styleUrls: ['./not-found.component.css']
})
export class NotFoundComponent implements OnInit {

  constructor() { }

  ngOnInit(): void {
  }

}
